### ISSUE TITLE
writelto doesn't seem to work well from going from tape to tape

### ISSUE THREAD

**Issue by dericed** [amiaopensource/ltopers#42]
I used `writelto -t some_tape_id /Volumes/another_tape_id` intending to copy a tape to another tape, but the tape being written to would throw errors and move to read only mode and act broken. I think copying via the gcp command in here doesn't work well from tape to tape, although rsync does. :-/ Some research needed, but maybe the copying method should be changed when the source is also an ltfs tape.

**Comment by retokromer** [comment]
Thank you for reporting this! Do you have any additional information about the error messages given by the drive? Do you use a desktop drive or a library? We did experience bad recording only rarely and, I guess, except very few power failures, all were tape issue and the tapes have been replaced by the manufacturers. I’ll check which are the differences between our programme and this one.

(I’ll also go through all the scripts in order to modify the TAPE_SERIAL_REGEX, as I just saw it on this one too.)

**Comment by retokromer** [comment]
So far I could not reproduce the error.

As long as I know, `gcp` should be **faster** than `rsync`. In the past I encountered performance issues with `rsync`, and I hand to use `--protocol 28` (or `--protocol 29` would possibly also had improved speed sufficiently), but not with today’s computers.

**Comment by dericed** [comment]
closing, i think it was a hardware issue
